### ISSUE TITLE
其他错误不管了吗？

### ISSUE THREAD

**Issue by mlboy** [qmdx00/Go-Camp#1]
https://github.com/qmdx00/Go-Camp/blob/a4964eea19aadecc23c70c644acaa6f2a6772484/week02/dao.go#L28

**Comment by qmdx00** [comment]
> https://github.com/qmdx00/Go-Camp/blob/a4964eea19aadecc23c70c644acaa6f2a6772484/week02/dao.go#L28
感谢指正，已修改。qmdx00@2c533e67b85e8422a6d97fff4c323ffb677c2b9e
